const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const ts = require('typescript');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const modules = new Map();
let cart, calls = 0;
function load(file) {
  file = path.resolve(file);
  if (modules.has(file)) return modules.get(file);
  const module = { exports: {} }; modules.set(file, module.exports);
  const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: {
    module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.ReactJSX,
  }}).outputText;
  vm.runInNewContext(code, {module,exports:module.exports,URLSearchParams,URL,console,require(name) {
    if (name.endsWith('.css')) return {__esModule:true,default:new Proxy({}, {get:(_,key)=>key})};
    if (name === 'next/link') return {__esModule:true,default:({children, ...props})=>React.createElement('a',props,children)};
    if (name === 'next/image') return {__esModule:true,default:({alt,src})=>React.createElement('img',{alt,src})};
    if (name === '@/lib/cart/CartProvider') return {useCart:()=>cart};
    if (name.startsWith('@/')) return load(path.join('src',name.slice(2))+'.ts');
    if (name.startsWith('.')) {const base=path.resolve(path.dirname(file),name);return load(fs.existsSync(base+'.tsx')?base+'.tsx':base+'.ts');}
    return require(name);
  }}, {filename:file});
  return module.exports;
}
const { normalizeCatalogListParams } = load('src/lib/catalog/query-params.ts');
const { catalogHref } = load('src/lib/catalog/url-state.ts');
const { evaluateCommerce } = load('src/lib/catalog/commerce.ts');
const { upsertLine, EMPTY_CART } = load('src/lib/cart/model.ts');
const { CatalogControls } = load('src/components/catalog/CatalogControls.tsx');
const { CatalogSort } = load('src/components/catalog/CatalogSort.tsx');
const { CatalogPagination } = load('src/components/catalog/CatalogPagination.tsx');
const { CategoryCatalog } = load('src/components/catalog/CategoryCatalog.tsx');
const { ProductGrid } = load('src/components/catalog/ProductGrid.tsx');
const { CardCartAction } = load('src/components/catalog/CardCartAction.tsx');
const params = normalizeCatalogListParams({categorySlug:'travertin', q:' Травертин ',price_min:'1600',price_max:'2100.50',sort:'price_desc',page:'3',status:'in_stock'});
const url = new URL(catalogHref(params),'https://example.test');
assert.equal(url.pathname,'/catalog/travertin');
assert.equal(url.searchParams.get('page'),null);
assert.equal(url.searchParams.get('q'),'Травертин');
assert.equal(url.searchParams.get('price_max'),'2100.50');
assert.equal(url.searchParams.get('status'),'in_stock');
assert.equal(url.searchParams.get('category'),null);
assert.equal(new URL(catalogHref(params,4),'https://example.test').searchParams.get('page'),'4');
assert.equal(new URL(catalogHref({...params,categorySlug:null}),'https://example.test').pathname,'/catalog');
assert.equal(new URL(catalogHref({...params,categorySlug:'gibkiy-mramor'}),'https://example.test').pathname,'/catalog/gibkiy-mramor');
const category={id:'c',slug:'travertin',name:'Травертин',sortOrder:0};
const facets={categories:[category],availabilityStatuses:[],fixedPriceMinor:{min:160000,max:210000}};
const html = renderToStaticMarkup(React.createElement(CatalogControls,{params,facets,total:1}));
assert.match(html,/action="\/catalog\/travertin"/);
assert.match(html,/href="\/catalog\/travertin">Сбросить/);
assert.match(html,/method="get"/);
assert.doesNotMatch(html,/name="category"|name="page"|name="status"/);
const links=[...html.matchAll(/href="([^"]+)"/g)].map(m=>m[1].replaceAll('&amp;','&'));
assert.ok(links.every(link=>!link.includes('status=')),'absent availability facet is not preserved by category navigation');
let submitted=0;CatalogSort({value:'order'}).props.onChange({currentTarget:{form:{requestSubmit:()=>submitted++}}});
assert.equal(submitted,1);
const pagination=renderToStaticMarkup(React.createElement(CatalogPagination,{params,total:100,pageSize:24}));
assert.match(pagination,/\/catalog\/travertin\?/);
assert.doesNotMatch(pagination,/href="\/catalog\?/);
const beyond=renderToStaticMarkup(React.createElement(CatalogPagination,{params:{...params,page:9},total:1,pageSize:24}));
assert.match(beyond,/К первой странице/);assert.doesNotMatch(beyond,/page=/);
const p={id:'test-component-only',slug:'technical-material',name:'Technical material',sku:'NOT-REAL',series:null,priceMinor:200000,currency:'RUB',priceUnit:'м²',saleUnit:'sheet',minQuantity:1,quantityStep:1,areaPerSaleUnitM2:4.0328,availabilityStatus:null,primaryImage:{url:'/technical-image',alt:'Preserved factual alt'},categories:[],isFeatured:false,sortOrder:0};
cart={state:EMPTY_CART,hydrationStatus:'ready',upsert:(id,quantity,rule,snapshot)=>{calls++;cart.state=upsertLine(cart.state,{productId:id,quantity,snapshot},rule).state;}};
const blocked=renderToStaticMarkup(React.createElement(ProductGrid,{products:[p],linkToDetail:true}));
assert.equal((blocked.match(/href="\/product\/technical-material"/g)||[]).length,3);
assert.match(blocked,/alt="Preserved factual alt"/);assert.match(blocked,/Подробнее/);
assert.doesNotMatch(blocked,/<button/);
const ready=evaluateCommerce({...p,availabilityStatus:'in_stock'},true);assert.equal(ready.commercialStatus,'ready');
const action=CardCartAction({productId:p.id,name:p.name,model:ready,snapshot:{name:p.name}});
action.props.onClick(); action.props.onClick();assert.equal(cart.state.lines.length,1);assert.equal(cart.state.lines[0].quantity,1);
const added=CardCartAction({productId:p.id,name:p.name,model:ready,snapshot:{name:p.name}});assert.equal(added.props.disabled,true);assert.match(added.props['aria-label'],/в корзине/);const before=calls;added.props.onClick();assert.equal(calls,before);
const hydration=CardCartAction({productId:p.id,name:p.name,model:ready,snapshot:{}});cart.hydrationStatus='hydrating';const hydrating=CardCartAction({productId:'other',name:'Other',model:ready,snapshot:{}});assert.equal(hydrating.props.disabled,true);cart.hydrationStatus='ready';
const full=renderToStaticMarkup(React.createElement(CategoryCatalog,{category,result:{products:[p],total:1,pageSize:24},facets,params,unfilteredTotal:1}));
assert.match(full,/role="search"/);assert.match(full,/name="price_min"/);assert.match(full,/name="sort"/);
const empty=renderToStaticMarkup(React.createElement(CategoryCatalog,{category,result:{products:[],total:0,pageSize:24},facets,params,unfilteredTotal:1}));assert.match(empty,/Материалы не найдены/);
console.log('PASS: category URL/query/page/reset/pagination, progressive GET/sort, scoped controls, factual facets, card detail/alt/commerce/hydration/idempotency and no-results component fixtures. No DB fixtures.');
