const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
let rows, updates, guard=0, invalidations=0, failAt=-1;
function client(){ return {from(table){assert.equal(table,'categories');let mutation=null,filters=[];return {select(){return this},order(){return this},update(value){assert.deepEqual(Object.keys(value),['sort_order']);mutation=value;return this},eq(k,v){filters.push([k,v]);return this},then(resolve){return Promise.resolve({data:rows.map(r=>({...r})).sort((a,b)=>a.sort_order-b.sort_order||a.id.localeCompare(b.id)),error:null}).then(resolve)},async maybeSingle(){if(updates.length===failAt)return {data:null,error:{code:'fixture'}};const r=rows.find(r=>filters.every(([k,v])=>r[k]===v));if(!r)return {data:null,error:null};updates.push({id:r.id,...mutation});Object.assign(r,mutation);return {data:{id:r.id},error:null}}};}}; }
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,console,require(name){if(name==='next/cache')return {updateTag(){invalidations++},revalidatePath(){invalidations++}};if(name==='@/lib/admin/require-admin')return {async requireAdminMutation(){guard++;return {supabase:client()}}};if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+'.ts');return require(name)}});cache.set(file,module.exports);return module.exports;}
const root='src/app/admin/(workspace)/categories/';const {moveCategory,validCategoryOrder,categoryOrderVersion}=load(root+'order-model.ts');const {saveCategoryOrder}=load(root+'order-actions.ts');
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',c='00000000-0000-4000-8000-000000000003';
const original=[{id:a,sort_order:5,name:'A',slug:'a',is_published:true},{id:b,sort_order:5,name:'B',slug:'b',is_published:false},{id:c,sort_order:8,name:'C',slug:'c',is_published:true}];
function reset(){rows=structuredClone(original);updates=[];failAt=-1;}
(async()=>{reset();assert.equal(validCategoryOrder([a,a,c],rows),false);assert.equal(validCategoryOrder(['system-all',b,c],rows),false);assert.equal(validCategoryOrder([a,b],rows),false);assert.equal(validCategoryOrder([c,a,b],rows),true);
assert.deepEqual(Array.from(moveCategory([a,b,c],2,0)),[c,a,b]);assert.deepEqual(Array.from(moveCategory([a,b,c],0,1)),[b,a,c]);const list=[a,b,c];assert.equal(moveCategory(list,0,-1),list);assert.deepEqual(list,[a,b,c]);
let result=await saveCategoryOrder([c,a,b],categoryOrderVersion(rows));assert.equal(result.ok,true);assert.deepEqual(rows.map(r=>[r.id,r.sort_order]),[[a,1],[b,2],[c,0]]);assert.deepEqual(rows.map(({sort_order,...r})=>r),original.map(({sort_order,...r})=>r));assert.equal(guard,1);assert.ok(invalidations>0);
const stored=structuredClone(rows);updates=[];result=await saveCategoryOrder([c,a,b],categoryOrderVersion(rows));assert.equal(result.ok,true);assert.equal(updates.length,0);assert.deepEqual(rows,stored);
reset();result=await saveCategoryOrder([a,b,c],'stale');assert.equal(result.ok,false);assert.equal(updates.length,0);result=await saveCategoryOrder([a,a,c],categoryOrderVersion(rows));assert.equal(result.ok,false);assert.equal(updates.length,0);
reset();failAt=1;result=await saveCategoryOrder([c,a,b],categoryOrderVersion(rows));assert.equal(result.ok,false);assert.match(result.message,/не полностью/);assert.equal(updates.length,1);assert.deepEqual(rows.map(({sort_order,...r})=>r),original.map(({sort_order,...r})=>r));
const component=fs.readFileSync(root+'CategoryOrderList.tsx','utf8');assert.match(component,/draggable=\{!pending\}/);assert.match(component,/onDrop/);assert.match(component,/onDragEnd/);assert.match(component,/index === 0/);assert.match(component,/index === rows.length - 1/);assert.match(component,/move\(index, index - 1\)/);assert.match(component,/move\(index, index \+ 1\)/);assert.match(component,/Все товары/);assert.match(component,/Сохранить порядок/);assert.doesNotMatch(component,/secret|service_role/);
console.log('PASS: guarded UPDATE sort_order only, duplicate/system/missing/stale rejection, deterministic normalization, immutable category fields, idempotent save, explicit partial failure, reorder move boundaries, drag/arrow wiring. Mock rows only.');})();
