const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
let products=[],categories=[],reads=[],env={},product=null;
const image={url:'https://example.supabase.co/storage/v1/object/public/product-media/products/fixture.webp',alt:'Подтверждённый alt',width:656,height:656,isPrimary:true};
function client(){return {from(table){const filters=[];let start=0,end=Infinity;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},is(k,v){filters.push(r=>r[k]===v);return q},order(){return q},range(a,b){start=a;end=b;return q},async maybeSingle(){return {data:(table==='products'?products:categories).find(r=>filters.every(f=>f(r)))??null,error:null}},then(resolve){reads.push({table,start});return Promise.resolve({data:(table==='products'?products:categories).filter(r=>filters.every(f=>f(r))).slice(start,end+1),error:null}).then(resolve)}};return q}}}
function load(file){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,URL,process:{env},require(name){if(name==='server-only')return {};if(name==='next/cache')return {unstable_cache:fn=>fn};if(name==='next/navigation')return {notFound(){throw new Error('NOT_FOUND')}};if(name==='@/lib/supabase/public')return {createPublicSupabaseClient:client};if(name==='@/lib/catalog/queries')return {catalogCacheTags:{list:'catalog:list',facets:'catalog:facets',category:s=>'catalog:category:'+s},getPublishedProduct:async()=>product};if(name.startsWith('@/lib/seo/'))return load('src/lib/seo/'+name.split('/').pop()+'.ts');if(name==='@/lib/catalog/query-params')return load('src/lib/catalog/query-params.ts');if(name==='./metadata'||name==='./public-catalog')return load('src/lib/seo/'+name.slice(2)+'.ts');return {}}},{filename:file});return module.exports}
const plain=v=>JSON.parse(JSON.stringify(v));
(async()=>{for(const mode of ['production','preview','development',undefined]){env={SITE_URL:'https://marmixflex.ru',VERCEL_ENV:mode,VERCEL_URL:'wrong.vercel.app'};const helper=load('src/lib/seo/dynamic.ts');const category={slug:'travertin',name:'Травертин',description:null,seoTitle:null,seoDescription:null};
let m=helper.catalogMetadata({},null);assert.equal(m.robots.index,mode==='production');assert.equal(m.alternates.canonical,'https://marmixflex.ru/catalog');assert.equal(m.openGraph.url,m.alternates.canonical);assert.equal(m.title.absolute,'Каталог — Marmix Flex');
for(const key of ['category','q','price_min','price_max','status','sort','page']){m=helper.catalogMetadata({[key]:'test'},key==='category'?category:null);assert.equal(m.robots.index,false);assert.equal(m.robots.follow,mode==='production');assert.ok(!m.alternates.canonical.includes('?'))}
m=helper.catalogMetadata({category:'travertin',sort:'price_asc'},category);assert.equal(m.alternates.canonical,'https://marmixflex.ru/catalog/travertin');m=helper.categoryMetadata(category,{});assert.equal(m.robots.index,mode==='production');assert.equal(m.openGraph.images,undefined);assert.match(m.description,/Материалы категории/);m=helper.categoryMetadata(category,{page:'2'});assert.equal(m.robots.index,false);
product={name:'Азур',slug:'azur',seoTitle:null,seoDescription:null,description:null,primaryImage:image};m=helper.productMetadata(product);assert.equal(m.title.absolute,'Азур — Marmix Flex');assert.equal(m.alternates.canonical,'https://marmixflex.ru/product/azur');assert.equal(m.openGraph.images[0].alt,image.alt);assert.equal(m.openGraph.images[0].url,image.url);assert.equal(m.robots.index,mode==='production');assert.doesNotMatch(m.description,/наличии|доставк|подходит/);
m=helper.productMetadata({...product,seoTitle:'Азур — Marmix Flex',seoDescription:'Подтверждённое SEO описание',description:'Fallback'});assert.equal(m.title.absolute,'Азур — Marmix Flex');assert.equal(m.description,'Подтверждённое SEO описание');assert.equal(helper.productMetadata({...product,primaryImage:null}).openGraph.images,undefined);
const robots=load('src/app/robots.ts').default();assert.equal(robots.rules.disallow,mode==='production'?robots.rules.disallow:'/');if(mode==='production'){assert.ok(robots.rules.disallow.includes('/admin'));assert.equal(robots.sitemap,'https://marmixflex.ru/sitemap.xml')}else assert.equal(robots.sitemap,undefined);
}
env={SITE_URL:'https://marmixflex.ru',VERCEL_ENV:'preview'};products=Array.from({length:501},(_,i)=>({id:String(i),slug:'real-'+i,catalog_kind:'REAL',is_published:true,archived_at:null}));products.push({id:'draft',slug:'draft',catalog_kind:'REAL',is_published:false,archived_at:null},{id:'archive',slug:'archive',catalog_kind:'REAL',is_published:true,archived_at:'x'},{id:'test',slug:'test',catalog_kind:'TEST_ONLY',is_published:true,archived_at:null});categories=[{slug:'travertin',name:'Травертин',is_published:true,description:null,seo_title:null,seo_description:null},{slug:'hidden',is_published:false}];
const pub=load('src/lib/seo/public-catalog.ts');assert.equal(await pub.getPublishedSeoCategory('hidden'),null);assert.equal(await pub.getPublishedSeoCategory('../hidden'),null);assert.equal((await pub.getPublishedSeoCategory('travertin')).name,'Травертин');
const sitemap=plain(await load('src/app/sitemap.ts').default());assert.equal(sitemap.length,6+501+1);assert.ok(reads.some(r=>r.table==='products'&&r.start===500));for(const row of sitemap){assert.deepEqual(Object.keys(row),['url']);assert.ok(row.url.startsWith('https://marmixflex.ru/'));assert.doesNotMatch(row.url,/\?|vercel|admin|cart|checkout|privacy|terms|draft|archive|test|hidden/)}
for(const route of ['src/app/(public)/catalog/[category]/page.tsx','src/app/(public)/product/[slug]/page.tsx']){product=null;await assert.rejects(load(route).generateMetadata({params:Promise.resolve({category:'hidden',slug:'draft'}),searchParams:Promise.resolve({})}),/NOT_FOUND/)}
const catalog=load('src/app/(public)/catalog/page.tsx');const invalid=await catalog.generateMetadata({searchParams:Promise.resolve({category:'hidden'})});assert.equal(invalid.alternates.canonical,'https://marmixflex.ru/catalog');assert.equal(invalid.robots.index,false);
for(const file of ['src/lib/seo/dynamic.ts','src/lib/seo/public-catalog.ts','src/app/sitemap.ts','src/app/robots.ts'])assert.doesNotMatch(fs.readFileSync(file,'utf8'),/service_role|createSecret|request\.headers|VERCEL_URL|application\/ld\+json|JSON-LD/);
console.log('PASS: production/Preview indexing matrix, filter canonicals, SEO precedence/brand, factual fallbacks, primary OG/alt and absent media; 501-row guest/RLS sitemap excludes draft/archive/TEST_ONLY/hidden/query/service; hidden/product notFound; robots SITE_URL; no structured data.');})().catch(e=>{console.error(e);process.exitCode=1});
