const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),React=require('react');
const root='src/app/admin/(workspace)/products/'; let cleanup,timer,delay,pushes=[];
class Input{constructor(name){this.name=name}}
function load(file){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{module,exports:module.exports,URLSearchParams,HTMLInputElement:Input,FormData:class{constructor(form){this.values=form.values}forEach(fn){Object.entries(this.values).forEach(([k,v])=>fn(v,k))}},setTimeout(fn,ms){timer=fn;delay=ms;return 1},clearTimeout(){timer=null},require(name){if(name==='react')return {...React,useRef:()=>({current:null}),useEffect:fn=>{cleanup=fn()},useTransition:()=>[false,fn=>fn()]};if(name==='next/navigation')return {useRouter:()=>({push:(...args)=>pushes.push(args)})};if(name==='./filter-url')return load(root+'filter-url.ts');if(name.endsWith('.css'))return {__esModule:true,default:{}};return require(name)}});return module.exports}
const {productFilterHref}=load(root+'filter-url.ts');assert.equal(productFilterHref(new URLSearchParams('page=8&view=order&sort=order')),'/admin/products');assert.equal(productFilterHref(new URLSearchParams('q=SKU&status=archived&category=abc&sort=name_desc&page=3')),'/admin/products?q=SKU&status=archived&category=abc&sort=name_desc');
const {ProductFilters}=load(root+'ProductFilters.tsx');const element=ProductFilters({children:null}),form=element.props.children[0];const currentTarget={values:{q:'Азур',status:'published',category:'abc',sort:'sku',page:'4'}};
form.props.onChange({currentTarget,target:new Input('q')});assert.equal(pushes.length,0);assert.equal(delay,400);timer();assert.equal(pushes.length,1);assert.equal(pushes[0][0],'/admin/products?q=%D0%90%D0%B7%D1%83%D1%80&status=published&category=abc&sort=sku');assert.equal(pushes[0][1].scroll,false);
for(const name of ['status','category','sort']){form.props.onChange({currentTarget,target:{name}});assert.equal(timer,null)}assert.equal(pushes.length,4);
form.props.onChange({currentTarget,target:new Input('q')});let prevented=false;form.props.onSubmit({currentTarget,preventDefault(){prevented=true}});assert.equal(prevented,true);assert.equal(timer,null);assert.equal(pushes.length,5);
form.props.onChange({currentTarget,target:new Input('q')});cleanup();assert.equal(timer,null);
const page=fs.readFileSync(root+'page.tsx','utf8');assert.doesNotMatch(page,/Применить/);assert.match(page,/Изменить порядок товаров/);assert.match(page,/key=\{JSON.stringify\(params\)\}/);assert.match(page,/href="\/admin\/products\?view=order"/);assert.match(page,/href="\/admin\/products">Сбросить/);
console.log('PASS: debounce 400ms; selects instant; Enter cancels debounce; unmount cancels timer; URL preserves filters and resets page; reset; server params key supports refresh/history; prominent reorder entry; no Apply.');
