// Restored technical harness. Mock rows only, no live writes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
let rows=[],updates=[],guard=0,failAt=-1,queries=[];
function client(){return {from(table){let filters=[],orders=[],start=0,end=Infinity,limit=Infinity,mutation=null;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},is(k,v){filters.push(r=>r[k]===v);return q},not(k,op,v){filters.push(r=>r[k]!==v);return q},in(k,vs){filters.push(r=>vs.includes(r[k]));return q},or(){return q},order(k,{ascending=true}={}){orders.push([k,ascending]);return q},range(a,b){start=a;end=b;return q},limit(n){limit=n;return q},update(value){assert.deepEqual(Object.keys(value),['sort_order']);mutation=value;return q},then(resolve){queries.push({table,start});let found=table==='products'?rows.filter(r=>filters.every(f=>f(r))):[];found=[...found].sort((a,b)=>{for(const [k,asc] of orders){const c=typeof a[k]==='number'?a[k]-b[k]:String(a[k]).localeCompare(String(b[k]));if(c)return asc?c:-c}return 0});return Promise.resolve({data:found.slice(start,Math.min(end+1,start+limit)),count:found.length,error:null}).then(resolve)},async maybeSingle(){if(updates.length===failAt)return {data:null,error:{code:'fixture'}};const r=rows.find(r=>filters.every(f=>f(r)));if(!r)return {data:null,error:null};updates.push({id:r.id,...mutation});Object.assign(r,mutation);return {data:{id:r.id},error:null}}};return q}}}
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,console,URLSearchParams,require(name){if(name==='server-only')return {};if(name==='next/cache')return {updateTag(){},revalidatePath(){},unstable_cache:fn=>fn};if(name==='@/lib/admin/require-admin')return {async requireAdminMutation(){guard++;return {supabase:client()}}};if(name==='@/lib/supabase/public')return {createPublicSupabaseClient:client};if(name==='react'&&file.endsWith('ProductNavigator.tsx'))return {...React,useState:()=>['',()=>{}]};if(name==='next/link')return {__esModule:true,default:({children,...props})=>React.createElement('a',props,children)};if(name.endsWith('.css'))return {__esModule:true,default:new Proxy({}, {get:(_,k)=>k})};if(name.startsWith('@/'))return load(path.resolve('src',name.slice(2))+'.ts');if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+'.ts');return require(name)}});cache.set(file,module.exports);return module.exports}
const root='src/app/admin/(workspace)/products/',id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const make=(n,extra={})=>({id:id(n),name:'Material '+n,sku:'SKU-'+n,sort_order:n,catalog_kind:'REAL',archived_at:null,is_published:true,is_featured:true,availability_status:null,price_minor:200000,...extra});
const baseline=[make(1,{sort_order:5}),make(2,{sort_order:5,is_published:false}),make(3,{sort_order:9}),make(4,{archived_at:'archived',sort_order:0}),make(5,{catalog_kind:'TEST_ONLY',sort_order:0})];
const {productOrderVersion,validProductOrder,moveProduct}=load(root+'order-model.ts'),{saveProductOrder}=load(root+'order-actions.ts'),{readProductOrder}=load(root+'order-read.ts'),{getRealProductsPage,parseProductListParams}=load(root+'products-list.ts'),{listPublishedFeaturedProducts}=load('src/lib/catalog/queries.ts'),{transitionPatch}=load(root+'[id]/assortment-validation.ts'),{ProductNavigator}=load(root+'[id]/ProductNavigator.tsx');
function reset(){rows=structuredClone(baseline);updates=[];failAt=-1;queries=[];}
(async()=>{reset();let order=await readProductOrder(client());assert.deepEqual(Array.from(order,r=>r.id),[id(1),id(2),id(3)]);for(const invalid of [[id(1),id(1),id(3)],[id(1),id(4),id(3)],[id(1),id(3)]])assert.equal(validProductOrder(invalid,order),false);
let result=await saveProductOrder([id(3),id(1),id(2)],productOrderVersion(order));assert.equal(result.ok,true);assert.equal(guard,1);assert.deepEqual(rows.slice(0,3).map(r=>r.sort_order),[1,2,0]);assert.deepEqual(rows.map(({sort_order,...r})=>r),baseline.map(({sort_order,...r})=>r));assert.deepEqual(rows.slice(3),baseline.slice(3));
updates=[];result=await saveProductOrder([id(3),id(1),id(2)],productOrderVersion(await readProductOrder(client())));assert.equal(result.ok,true);assert.equal(updates.length,0);
reset();result=await saveProductOrder([id(3),id(1),id(2)],'stale');assert.equal(result.ok,false);assert.equal(updates.length,0);
reset();failAt=1;result=await saveProductOrder([id(3),id(1),id(2)],productOrderVersion(await readProductOrder(client())));assert.equal(result.ok,false);assert.match(result.message,/не полностью/);assert.deepEqual(rows.map(({sort_order,...r})=>r),baseline.map(({sort_order,...r})=>r));
let list=[1,2,3];assert.equal(moveProduct(list,0,-1),list);assert.deepEqual(Array.from(moveProduct(list,2,0)),[3,1,2]);assert.deepEqual(list,[1,2,3]);
rows=Array.from({length:501},(_,i)=>make(i+1));queries=[];assert.equal((await readProductOrder(client())).length,501);assert.deepEqual(queries.map(q=>q.start),[0,500]);
for(const n of [1,2,3,4,5,6,9]){rows=Array.from({length:n},(_,i)=>make(i+1,{sort_order:0})).reverse();rows.push(make(100,{is_featured:false}),make(101,{catalog_kind:'TEST_ONLY'}),make(102,{archived_at:'x'}),make(103,{is_published:false}));const featured=await listPublishedFeaturedProducts();assert.equal(featured.length,Math.min(n,6));assert.deepEqual(Array.from(featured,p=>p.id),Array.from({length:Math.min(n,6)},(_,i)=>id(i+1)));}
reset();const params=parseProductListParams({},[]);let page=await getRealProductsPage(client(),params);assert.deepEqual(Array.from(page.products,p=>p.id),[id(1),id(2),id(3)]);page=await getRealProductsPage(client(),{...params,status:'archived'});assert.equal(page.total,1);assert.equal(page.products[0].id,id(4));const patch=transitionPatch('restore',{is_published:false,archived_at:'x'});assert.equal(patch.patch.archived_at,null);assert.equal(patch.patch.is_published,false);Object.assign(rows.find(r=>r.id===id(4)),patch.patch);page=await getRealProductsPage(client(),params);assert.equal(page.total,4);
rows=Array.from({length:70},(_,i)=>make(i+1));const html=renderToStaticMarkup(React.createElement(ProductNavigator,{products:rows,current:rows[1]}));for(const text of ['aria-current="page"','Сохраните изменения перед переходом','Мобильный список товаров','Следующий','Предыдущий','Показаны 50 результатов'])assert.ok(html.includes(text));assert.doesNotMatch(html,/Material 51</);assert.ok(html.includes('/admin/products/'+id(3)));assert.ok(html.includes('/admin/products/'+id(1)));
const source=fs.readFileSync(root+'page.tsx','utf8');assert.ok(source.indexOf('raw.view === "order"')<source.indexOf('parseProductListParams(raw'));assert.match(source,/Все активные/);assert.doesNotMatch(fs.readFileSync(root+'order-actions.ts','utf8'),/\.delete\(|\.insert\(|\.upsert\(|secret|service_role/);
console.log('PASS: complete active REAL global sort-only reorder, stale/duplicate/archive rejection, immutable fields, partial failures, idempotency, 501-row batch read; Featured 1..6/>6 eligibility and ties; default/archive/restore; active navigator, neighbors, 50-results, mobile and save notice. Mock data only.');})().catch(e=>{console.error(e);process.exitCode=1});
